services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brotkrueml\SchemaAuto\:
    resource: '../Classes/*'

  Brotkrueml\SchemaAuto\EventListener\RegisterAdditionalProperties:
    tags:
      - name: event.listener
        identifier: 'ext-schema-auto/registerAdditionalProperties'
